#!/bin/bash

CURRENT_WINDOWS=$(bspc query -N -d focused)
CURRENT_DESKTOP_ID=$(bspc query -D -d focused)

if [ -f "$HOME/.cache/bspwm/$CURRENT_DESKTOP_ID" ]; then
	exit
fi


echo $$ > ~/.cache/bspwm/$CURRENT_DESKTOP_ID

for node_id in $CURRENT_WINDOWS; do
	bspc node $node_id -t floating
done

bspc subscribe node_add | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[4]}
    [ "$CURRENT_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
